# Generated by Django 5.2.12 on 2026-03-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[("rss", "RSS Feed"), ("urls", "URL List")],
                        max_length=10,
                    ),
                ),
                (
                    "input_source",
                    models.TextField(
                        help_text="RSS URL or newline-separated article URLs"
                    ),
                ),
                ("source_article_count", models.PositiveIntegerField(default=0)),
                ("generated_title", models.CharField(blank=True, max_length=500)),
                ("generated_article", models.TextField(blank=True)),
                ("jewelry_topic", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
